unbind C-b
set -g prefix `
bind ` send-prefix

set-environment -g TINTED_TMUX_OPTION_ACTIVE "1"
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"
set -ag terminal-overrides ",*:Tc"
set -g allow-passthrough on

set -g base-index 1
set -g pane-base-index 1

set -g status on

set -g status-bg default
set -g status-fg default
set -g status-justify absolute-centre

set -g status-left-length 30
set -g status-right-length 30
set -g status-left '#[fg=default]#S #[fg=default]#I:#P'
set -g status-right ''

setw -g window-status-current-style 'fg=black bg=colour1'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=colour1 bg=default'
setw -g window-status-format ' #I #[fg=default]#W #[fg=colour3]#F '

setw -g window-status-bell-style 'fg=colour3 bg=colour1 bold'

set -g renumber-windows on
set -s copy-command 'wl-copy'
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g escape-time 0
set -g mouse on
set -g repeat-time 1000
set -g history-limit 500
set-option -g focus-events on

# keybinds
#bind  split-window -h
bind | split-window -h

bind v split-window -v
bind - split-window -v

bind f resize-pane -Z

bind r source-file ~/.config/tmux/tmux.conf

