# changinf leader
unbind C-b
set -g prefix `
bind ` send-prefix

# 1 based index
set -g base-index 1
set -g pane-base-index 1

# colors
set -g default-terminal "${TERM}"
set-option -g default-terminal "screen-256color"
set -sg terminal-overrides ",*:RGB"

# Status bar
set -g status-style bg=default,fg=black,bright
set -g status-left ""
set -g status-right "#[fg=black,bright]#S"

# WIndow
set -g window-status-format ""
set -g window-status-current-format ""

set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta,nobold}"

set -g window-status-bell-style "fg=red,nobold"

# options
set -g renumber-windows on
set -s copy-command 'wl-copy'
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'

# Qol
set -g escape-time 0
set -g mouse on
set -g repeat-time 1000
set -g history-limit 500
set-option -g focus-events on

# keybinds
#bind  split-window -h
bind | split-window -h

bind v split-window -v
bind - split-window -v

bind f resize-pane -Z


